### ISSUE TITLE
Confusing English string "Assign Paper"

### ISSUE THREAD

**Issue by mudrd8mz** [EduardoKrausME/moodle-enrol-paymentpagseguro#1]
In the instance edit form, there is a field called "Assign Paper". I found it a bit confusing. Given the help popup for it, should it read "Assign role" ?

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-enrol-paymentpagseguro/commit/635ef268b67544eb5d042701f96ed46164ce93e2
