### ISSUE TITLE
Invalid & confusing license notice in PagSeguroLibrary libraries

### ISSUE THREAD

**Issue by mudrd8mz** [EduardoKrausME/moodle-enrol-paymentpagseguro#2]
The PagSeguroLibrary has its own Apache 2.0 license. It is not valid to simply prepend Moodle GPL header to their files. Correct is to leave their files as-are and declare the usage of 3rd party library via the file https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-enrol-paymentpagseguro/commit/84eff724d0b3bd537984b2181c375d98d102b9af
