### ISSUE TITLE
Misuse of the classes folder

### ISSUE THREAD

**Issue by mudrd8mz** [EduardoKrausME/moodle-enrol-paymentpagseguro#3]
You have put the PagSeguroLibrary into the "classes" directory within your plugin. That is not expected. This folder is supposed to hold just the classes supported by Moodle's inbuild autoloading mechanism, following the naming guidelines and namespacing rules.

Let me suggest to move the PagSeguroLibrary into a standalone directory.

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-enrol-paymentpagseguro/commit/5ffc75734c4478603f0aee69dabf6aa346a70eb2
