### ISSUE TITLE
thirdpartylibs more complex than needed

### ISSUE THREAD

**Issue by danmarsden** [EduardoKrausME/moodle-enrol-paymentpagseguro#4]
thirdpartylibs just needs a single entry with location set to:
<location>vendor/pagseguro</location>

You do not need to list every file.

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-enrol_paymentpagseguro/commit/fabf6b62388010c6d6c156b93451095dbcee2e9e

**Comment by danmarsden** [comment]
you have misunderstood 

the thirdpartylibs.xml file is incorrect:
https://github.com/EduardoKrausME/moodle-enrol_paymentpagseguro/blob/master/thirdpartylibs.xml

you only need one entry that refers to PagSeguroLibrary and the main folder location. Not a reference to every file within the library.
