### ISSUE TITLE
missing privacy api

### ISSUE THREAD

**Issue by danmarsden** [EduardoKrausME/moodle-enrol-paymentpagseguro#5]
As mentioned by David on CONTRIB-7192:

The plugin shares users' full names and emails with a 3rd party. This should be clearly highlighted in the description and via the privacy API implementation.

more information on the privacy api is here:
https://docs.moodle.org/dev/Privacy_API

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-enrol_paymentpagseguro/commit/268ca7dcee35328e322470c6176ea7d967737315

**Comment by danmarsden** [comment]
you have implemented the null provider which is incorrect as you share user full names and e-mails with a 3rd party. You need to implement the external_link_location function as documented here:
https://docs.moodle.org/dev/Privacy_API#Indicating_that_you_export_data_to_an_external_location

here is an exmaple of a plugin that does this:
https://github.com/catalyst/moodle-tool_coursebank/blob/master/classes/privacy/provider.php

That example only passes the userid, but your plugin passes other data so you will need to update it to list all the data you send to the external service.
