### ISSUE TITLE
invalid use of PARAM_RAW

### ISSUE THREAD

**Issue by danmarsden** [EduardoKrausME/moodle-enrol-paymentpagseguro#6]
PARAM_RAW should only be used when there is no other option and when parameter cleaning is performed somewhere else. Some of these looked like they should have been PARAM_INT - others might need to be PARAM_TEXT - I don't think any of them should be PARAM_RAW.

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-enrol_paymentpagseguro/commit/e794e26a42403930b2a5d27961f93c38a9d47e9b
