### ISSUE TITLE
Tela branca (sem erros no log)

### ISSUE THREAD

**Issue by afmpjr** [EduardoKrausME/moodle-enrol-paymentpagseguro#7]
Salve! Belíssimo trabalho esse!
Eu acabei de fazer a instalação e parametrização do plugin, aparentemente com sucesso.

Infelizmente, quando vou adicionar o método de inscrição, seleciono "Instalação com pagamento pelo PagSeguro", sou redirecionado para o endereço ".../enrol/paymentpagseguro/edit.php?courseid=20" e não passa daí. Tela branca, sem log de erro.

Obrigado.

**Comment by afmpjr** [comment]
Contornei a situação, comentando a linha 25 
`// defined('MOODLE_INTERNAL') || die();`

Mas o formulário não grava as configurações quando clico em "Adicionar método"

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-enrol_paymentpagseguro/commit/5a5ff2f238f043ecc0a76c2b6ac91fd46d373d26
